// Regenerates frontend/src/abis.js from the compiled artifacts so the UI stays
// in lockstep with the contracts. Run after `npm run compile`; or `npm run abis`.
const fs = require("fs");
const path = require("path");

const NAMES = ["Stasis", "CowNFT", "CowRating", "Attestation", "GeneralPool", "HerdCouncil"];
const out = {};

for (const name of NAMES) {
  const file = path.join(__dirname, "..", "artifacts", "contracts", `${name}.sol`, `${name}.json`);
  const { abi } = JSON.parse(fs.readFileSync(file, "utf8"));
  // camelCase key, e.g. CowRating -> cowRating
  out[name[0].toLowerCase() + name.slice(1)] = abi;
}

const dest = path.join(__dirname, "..", "frontend", "src", "abis.js");
fs.mkdirSync(path.dirname(dest), { recursive: true });
fs.writeFileSync(dest, `// Generated by scripts/gen-abis.js — do not edit by hand.\nexport default ${JSON.stringify(out, null, 2)};\n`);
console.log("wrote", dest);